spring:
  datasource:
    url: jdbc:oracle:thin:@db202204291622_high?TNS_ADMIN=/home/ubuntu/app/wallet
    username: admin
    password: dbPassword
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081

nyTimes:
  baseUrl: https://api.nytimes.com/svc/search/v2/articlesearch.json
  queryParameters:
    sort: newest
    api-key: apiKey

newsApi:
  baseUrl: https://newsapi.org/v2/everything
  queryParameters:
    apiKey: apiKey
    sortBy: publishedAt
    language: en
