spring:
  datasource:
    url: jdbc:oracle:thin:@db202204291622_high\?TNS_ADMIN=/Users/janangandhi/Documents/Projects/CC/Wallet_DB202204291622
    username: admin
    password: db-password
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081

nyTimes:
  baseUrl: https://api.nytimes.com/svc/search/v2/articlesearch.json
  queryParameters:
    sort: newest
    api-key: apiKey
